export const MAIN_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/register'
export const DEVICE_ROUTE = '/device'